version: "3"
networks:
  node-ng-mysql:
    driver: "bridge"
services:
  db:
    build: ./db
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - 3300:3306
    env_file:
      - ./development.env
    networks:
      - node-ng-mysql
    volumes:
      - ./db/mysql-ecommerce:/var/lib/mysql
  backend:
    build: ./backend
    ports:
      - 3000:3000
    links:
      - db
    restart: always
    volumes:
      - ./backend:/usr/src/app
      - /usr/scr/app/node_modules
    networks:
      - node-ng-mysql

volumes:
  mysql-ecommerce:
